swipe:
  3: 
    left: 
      command: 'xdotool key alt+Right'
    right: 
      command: 'xdotool key alt+Left'
    up: 
      command: 'xdotool key Home'
    down: 
      command: 'xdotool key End'
  4:
    left:
      command: 'xdotool key ctrl+Page_Up'
    right:
      command: 'xdotool key ctrl+Page_Down'
    up:
      command: 'xdotool key ctrl+t'
    down:
      command: 'xdotool key ctrl+w'

# hold:
#   3:
#     command: 'xdotool key alt+Tab'
rotate:
  2:
    clockwise:
      command: 'xdotool key ctrl+w'
    counterclockwise:
      command: 'xdotool key ctrl'

pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.2
  pinch: 0.5

interval:
  swipe: 1
  pinch: 1
